/**
 * Reserved sentinel tenant for global / anonymous identity-auth events that have
 * no real tenant (login, logout, refresh, password) — see ADR 0007. Global
 * events form a single hash chain under this id; tenant-scoped events chain under
 * their real tenant. Keeps audit_entries.tenant_id NOT NULL with zero schema
 * deviation.
 */
export const SENTINEL_TENANT_ID = '00000000-0000-0000-0000-000000000000';

export type AuditActorType = 'user' | 'anonymous' | 'system' | 'terminal';

export const AUDIT_ACTION = {
  // P1A Sales. Canonical verbs follow the repository's existing
  // <ENTITY>_<PAST_TENSE> convention (FR-AUD-002 "canonical verb").
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATE_CHANGED: 'ORDER_STATE_CHANGED',
  // P1C line capture. Same <ENTITY>_<PAST_TENSE> convention; no new taxonomy
  // shape is introduced, only the two verbs the new commands actually perform.
  ORDER_LINE_ADDED: 'ORDER_LINE_ADDED',
  ORDER_LINE_VOIDED: 'ORDER_LINE_VOIDED',
  // P1D-1 Workforce / Treasury. Same <ENTITY>_<PAST_TENSE> convention; the
  // audit taxonomy is not governance-controlled, so these follow the existing
  // shape rather than inventing one. Opening a shift and taking custody of a
  // drawer are two separately accountable events, hence two verbs.
  SHIFT_OPENED: 'SHIFT_OPENED',
  CASH_SESSION_OPENED: 'CASH_SESSION_OPENED',
  // D-2 (amended) PIN substrate. Security-sensitive state changes only; a PIN
  // value never appears in any payload.
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_BRANCH_ASSIGNED: 'EMPLOYEE_BRANCH_ASSIGNED',
  PIN_SET: 'PIN_SET',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  TENANT_SELECTED: 'TENANT_SELECTED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  TERMINAL_REGISTERED: 'TERMINAL_REGISTERED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  // Phase 15 — Organisation configuration mutations (ADR 0008 §15). Reads are
  // deliberately NOT audited.
  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRANCH_CREATED: 'BRANCH_CREATED',
  BRANCH_UPDATED: 'BRANCH_UPDATED',
  BRANCH_STATUS_CHANGED: 'BRANCH_STATUS_CHANGED',
  /** FR-PLT-004 requires a full audit record for this operation. */
  BRANCH_BRAND_REASSIGNED: 'BRANCH_BRAND_REASSIGNED',
  WAREHOUSE_CREATED: 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED: 'WAREHOUSE_UPDATED',
  CENTRAL_KITCHEN_CREATED: 'CENTRAL_KITCHEN_CREATED',
  CENTRAL_KITCHEN_UPDATED: 'CENTRAL_KITCHEN_UPDATED',
  STATION_CREATED: 'STATION_CREATED',
  STATION_UPDATED: 'STATION_UPDATED',
  TABLE_CREATED: 'TABLE_CREATED',
  TABLE_UPDATED: 'TABLE_UPDATED',
  OPERATING_HOURS_CREATED: 'OPERATING_HOURS_CREATED',
  OPERATING_HOURS_UPDATED: 'OPERATING_HOURS_UPDATED',
  PRINT_ROUTING_CREATED: 'PRINT_ROUTING_CREATED',
  PRINT_ROUTING_UPDATED: 'PRINT_ROUTING_UPDATED',
  STATION_ROUTING_CREATED: 'STATION_ROUTING_CREATED',
  STATION_ROUTING_UPDATED: 'STATION_ROUTING_UPDATED',

  // Phase 16 — Catalogue mutations. Reads are NOT audited.
  MENU_CREATED: 'MENU_CREATED',
  MENU_UPDATED: 'MENU_UPDATED',
  MENU_ACTIVATED: 'MENU_ACTIVATED',
  MENU_DEACTIVATED: 'MENU_DEACTIVATED',
  MENU_BRANCH_ASSIGNED: 'MENU_BRANCH_ASSIGNED',
  MENU_BRANCH_UNASSIGNED: 'MENU_BRANCH_UNASSIGNED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  MENU_ITEM_CREATED: 'MENU_ITEM_CREATED',
  MENU_ITEM_UPDATED: 'MENU_ITEM_UPDATED',
  MENU_ITEM_ACTIVATED: 'MENU_ITEM_ACTIVATED',
  MENU_ITEM_DEACTIVATED: 'MENU_ITEM_DEACTIVATED',
  MENU_ITEM_PLACED: 'MENU_ITEM_PLACED',
  MENU_ITEM_UNPLACED: 'MENU_ITEM_UNPLACED',
  VARIANT_CREATED: 'VARIANT_CREATED',
  VARIANT_UPDATED: 'VARIANT_UPDATED',
  VARIANT_ACTIVATED: 'VARIANT_ACTIVATED',
  VARIANT_DEACTIVATED: 'VARIANT_DEACTIVATED',
  MODIFIER_GROUP_CREATED: 'MODIFIER_GROUP_CREATED',
  MODIFIER_GROUP_UPDATED: 'MODIFIER_GROUP_UPDATED',
  MODIFIER_CREATED: 'MODIFIER_CREATED',
  MODIFIER_UPDATED: 'MODIFIER_UPDATED',
  MODIFIER_GROUP_LINKED: 'MODIFIER_GROUP_LINKED',
  PRICE_LIST_CREATED: 'PRICE_LIST_CREATED',
  PRICE_LIST_UPDATED: 'PRICE_LIST_UPDATED',
  /** FR-MNU-024: the audit trail is the system of record for price history. */
  PRICE_ENTRY_SET: 'PRICE_ENTRY_SET',
  AVAILABILITY_RULE_CREATED: 'AVAILABILITY_RULE_CREATED',
  AVAILABILITY_86_TOGGLED: 'AVAILABILITY_86_TOGGLED',

  // Inventory — mutations. Reads are NOT audited.
  STOCK_ITEM_CREATED: 'STOCK_ITEM_CREATED',
  STOCK_ITEM_UPDATED: 'STOCK_ITEM_UPDATED',
  REASON_CODE_CREATED: 'REASON_CODE_CREATED',
  REORDER_CONFIG_SET: 'REORDER_CONFIG_SET',
  STOCK_MOVEMENT_RECORDED: 'STOCK_MOVEMENT_RECORDED',
  STOCK_TRANSFER_DISPATCHED: 'STOCK_TRANSFER_DISPATCHED',
  STOCK_TRANSFER_RECEIVED: 'STOCK_TRANSFER_RECEIVED',
  COUNT_SESSION_OPENED: 'COUNT_SESSION_OPENED',
  COUNT_SESSION_POSTED: 'COUNT_SESSION_POSTED',
  WASTE_RECORDED: 'WASTE_RECORDED',

  // Production Spec — recipe lifecycle.
  RECIPE_CREATED: 'RECIPE_CREATED',
  RECIPE_VERSION_CREATED: 'RECIPE_VERSION_CREATED',
  RECIPE_VERSION_UPDATED: 'RECIPE_VERSION_UPDATED',
  RECIPE_VERSION_PUBLISHED: 'RECIPE_VERSION_PUBLISHED',
  SUBSTITUTE_GROUP_CREATED: 'SUBSTITUTE_GROUP_CREATED',
  SUBSTITUTE_GROUP_UPDATED: 'SUBSTITUTE_GROUP_UPDATED',
} as const;

export const AUDIT_ENTITY = {
  ORDER: 'order',
  ORDER_LINE: 'order_line',
  SHIFT: 'shift',
  CASH_SESSION: 'cash_session',
  DRAWER: 'drawer',
  EMPLOYEE: 'employee',
  USER: 'user',
  SESSION: 'session',
  TENANT: 'tenant',
  MEMBERSHIP: 'membership',
  TERMINAL: 'terminal',

  // Phase 15 — Organisation entities.
  BRAND: 'brand',
  BRANCH: 'branch',
  WAREHOUSE: 'warehouse',
  CENTRAL_KITCHEN: 'central_kitchen',
  STATION: 'station',
  TABLE: 'table',
  OPERATING_HOURS: 'operating_hours',
  PRINT_ROUTING: 'print_routing',
  STATION_ROUTING_RULE: 'station_routing_rule',

  // Phase 16 — Catalogue entities.
  MENU: 'menu',
  MENU_BRANCH: 'menu_branch',
  CATEGORY: 'category',
  MENU_ITEM: 'menu_item',
  MENU_ITEM_PLACEMENT: 'menu_item_placement',
  VARIANT: 'menu_item_variant',
  MODIFIER_GROUP: 'modifier_group',
  MODIFIER: 'modifier',
  MODIFIER_GROUP_LINK: 'modifier_group_link',
  PRICE_LIST: 'price_list',
  PRICE_ENTRY: 'price_entry',
  AVAILABILITY_RULE: 'availability_rule',

  // Inventory entities.
  STOCK_ITEM: 'stock_item',
  REASON_CODE: 'reason_code',
  REORDER_CONFIG: 'reorder_config',
  STOCK_MOVEMENT: 'stock_movement',
  COUNT_SESSION: 'count_session',
  WASTE_RECORD: 'waste_record',

  // Production Spec entities.
  RECIPE: 'recipe',
  RECIPE_VERSION: 'recipe_version',
  SUBSTITUTE_GROUP: 'substitute_group',
} as const;
